//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraiHeo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int id { get; set; }
        public int XuatChuongMin { get; set; }
        public int XuatChuongMax { get; set; }
        public int MonthXuatChuongMin { get; set; }
        public int MonthXuatChuongMax { get; set; }
        public int TuoiNhapDan { get; set; }
        public int CanHuyet { get; set; }
        public int TuoiPhoiGiongDuc { get; set; }
        public int TuoiPhoiGiongCai { get; set; }
        public int RePhoiGiongDuc { get; set; }
        public int RePhoiGiongCai { get; set; }
        public int ThucAnMotNgay { get; set; }
        public int ThucAnMax { get; set; }
        public int SoNgayMangThai { get; set; }
        public int SoNgayCaiSua { get; set; }
    }
}
